### ISSUE TITLE
Command history forgets typed command when user returned to own input string

### ISSUE THREAD

**Issue by jfeltkamp** [rackberg/para#16]
When I begin to type a command and go to the history with the arrow-up key and return to my own string with arrow-down the shell has forgotten my typed string.

**Comment by rackberg** [comment]
@jfeltkamp I have commited a fix for that.

Currently I've not created a new release, so in order to install the fix on your machine you need to update para to the latest master commit.

Simply execute `para self-update --unstable` to get the latest changes.

It would be nice if you confirm the new feature here. After that I will create a new stable release.

**Comment by jfeltkamp** [comment]
Nice work. Works great.
